# Generated by Django 5.2.5 on 2025-08-29 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='carmake',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carmake',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='dealer_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('WAGON', 'Wagon'), ('TRUCK', 'Truck'), ('VAN', 'Van'), ('SPORTS', 'Sports Car'), ('HATCHBACK', 'Hatchback'), ('COUPE', 'Coupe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
